# Generated by Django 4.2.9 on 2024-09-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_vps_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_topup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='vps_len',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
